namespace AI.BT
{
    public enum TaskType
    {
        GUARD_IS_ALARMED,
        GUARD_IS_CHAR_VISIBLE,
        GUARD_IS_CURIOUS,
        GUARD_IS_LAST_PERCIEVED_POSITION_REACHED,
        GUARD_IS_PLAYER_REACHED,
        GUARD_IS_LAST_NODE_REACHED,
        GUARD_IS_WAITING,
        GUARD_IS_OTHER_ALARMED,
        GUARD_CHAR_CHASE,
        GUARD_ALARMED,
        GUARD_RANDOM_PATROL,
        GUARD_REACH_LAST_PERCIEVED_POSITION,
        GUARD_STOP,
        GUARD_CHECK_NAVPOINT,
        GUARD_WAIT_NAVPOINT,
        GUARD_PATROL,
        GUARD_START_WAITING,
        GUARD_SWITCH_NAVPOINT,
        GUARD_DEFEAT_PLAYER,
        QUEST_NPC_GIVE_REWARD,
        QUEST_NPC_IDLE,
        QUEST_NPC_QUEST_NOT_COMPLETED,
        QUEST_NPC_REQUEST,
        QUEST_NPC_WATCH_PLAYER,
        QUEST_NPC_HAS_PLAYER_INTERACTED,
        QUEST_NPC_HAS_SAW_PLAYER,
        QUEST_NPC_IS_QUEST_AVAILABLE,
        QUEST_NPC_IS_QUEST_COMPLETED,
        SELECTOR,
        SEQUENCER
    }

}
